version: 2

jobs:
  build:
    working_directory: ~/consultation-gouv/consultation.gouv.fr
    parallelism: 1
    shell: /bin/bash --login
    environment:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    docker:
      - image: circleci/ruby:2.3
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec jekyll --version
      # below are the tests
      - run: bundle exec jekyll doctor
      - run: bundle exec jekyll build
      - run: grep "css/main.css" _site/index.html

  deploy:
    working_directory: ~/consultation-gouv/consultation.gouv.fr
    parallelism: 1
    shell: /bin/bash --login
    docker:
      - image: circleci/ruby:2.3
    steps:
      - add_ssh_keys:
          fingerprints:
            - "06:45:ff:9c:7f:45:07:79:4c:f9:2e:99:d4:64:1f:3b"
      - checkout
      - run: eval `ssh-agent` && ssh-add ~/.ssh/id_rsa* && ./deploy.sh ${CIRCLE_BRANCH}

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: [pprod, production]

